/** Evidence URLs kept per signal. */
export const MAX_EVIDENCE_URLS = 5;
/** How far back a post can be and still count as recent: about eighteen months, an album cycle. */
export const RECENT_WINDOW_DAYS = 548;
/** Below this many recent posts, signals come from the whole history rather than a thin window. */
export const MIN_POSTS_FOR_SIGNALS = 30;
/** Own posts with a positive metric needed before a median means anything. */
export const MIN_SAMPLES_FOR_MEDIAN = 5;
/** A post stands out at this multiple of the artist's own median. */
export const STANDOUT_MULTIPLE = 3;
/** Hashtags and repeated phrases are deliberate enough that two uses make a theme. */
export const MIN_THEME_COUNT = 2;
/** A plain caption word with no proper-noun evidence needs this many posts before it's trusted. */
export const MIN_THEME_COUNT_GENERIC_WORD = 5;
export const MAX_THEME_TERM_LEN = 40;
export const MIN_PHRASE_WORD_LEN = 4;

/** Reflexives, auxiliaries and fillers: words that survive naive frequency
 *  counting ("myself", "just", "thing") without ever being a real theme. */
export const CAPTION_STOPWORDS = new Set([
  // original core list
  "this",
  "that",
  "with",
  "from",
  "have",
  "just",
  "your",
  "about",
  "when",
  "what",
  "really",
  "there",
  "their",
  "been",
  "will",
  "were",
  "they",
  "them",
  "then",
  "than",
  "also",
  "some",
  "more",
  "much",
  "very",
  "like",
  "only",
  "even",
  "into",
  "over",
  "after",
  "before",
  "because",
  "while",
  "where",
  "which",
  "would",
  "could",
  "should",
  "being",
  "doing",
  "going",
  "gonna",
  "wanna",
  "dont",
  "cant",
  "didnt",
  "youre",
  "here",
  "come",
  "came",
  "make",
  "made",
  "know",
  "knew",
  "want",
  "need",
  "getting",
  "back",
  "still",
  "many",
  "these",
  "those",
  "always",
  "never",
  "such",
  "everyone",
  "everybody",
  "something",
  "someone",
  "thank",
  "thanks",
  // reflexives
  "myself",
  "yourself",
  "himself",
  "herself",
  "itself",
  "ourselves",
  "yourselves",
  "themselves",
  // auxiliaries / copulas
  "was",
  "are",
  "am",
  "does",
  "did",
  "doing",
  "done",
  "shall",
  "must",
  "might",
  "wont",
  "isnt",
  "arent",
  "wasnt",
  "werent",
  "hasnt",
  "hadnt",
  "doesnt",
  "havent",
  "couldnt",
  "wouldnt",
  "shouldnt",
  // vague fillers / hedges
  "thing",
  "things",
  "stuff",
  "lot",
  "lots",
  "bit",
  "way",
  "ways",
  "gotta",
  "yeah",
  "okay",
  "alright",
  "totally",
  "honestly",
  "definitely",
  "probably",
  "maybe",
  "pretty",
  "actually",
  "basically",
  "literally",
  "kind",
  "sort",
  "little",
  "big",
  "good",
  "great",
  "nice",
  "cool",
]);
